#!/bin/bash

echo "Press any key to start"
read -rsn1

start=$(date +%s.%N)

echo "Timing... press any key to stop"
while true; do
   	now=$(date +%s.%N)
        elapsed=$(echo "$now - $start" | bc -l)

    	printf "\rTime: %.2f" "$elapsed"
	read -rsn1 -t 0.1 key && break
done
echo
